//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentReq
    {
        public int AgentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string NationalID { get; set; }
        public string Birthday { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public string CompanyName { get; set; }
        public string startDate { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string PostalCode { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
        public string description { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
