//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public System.Guid BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string EN_BlogTitle { get; set; }
        public string BlogName { get; set; }
        public string BlogText { get; set; }
        public string EN_BlogText { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string BlogImage { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.Guid> fk_BlogGroupID { get; set; }
        public Nullable<System.Guid> fk_UserID { get; set; }
        public Nullable<int> VisitCounts { get; set; }
        public string Rus_BlogTitle { get; set; }
        public string China_BlogTitle { get; set; }
        public string Rus_BlogText { get; set; }
        public string China_BlogText { get; set; }
        public string BlogSummery { get; set; }
        public string EN_BlogSummery { get; set; }
        public string Rus_BlogSummery { get; set; }
        public string China_BlogSummery { get; set; }
    
        public virtual BlogGroups BlogGroups { get; set; }
    }
}
