//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colors
    {
        public Colors()
        {
            this.ProductColors = new HashSet<ProductColors>();
        }
    
        public int ColorID { get; set; }
        public string ColorName { get; set; }
        public string ColorTitle { get; set; }
        public string ColorEN_Title { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string ColorNo { get; set; }
        public string Rus_ColorTitle { get; set; }
        public string China_ColorTitle { get; set; }
    
        public virtual ICollection<ProductColors> ProductColors { get; set; }
    }
}
