//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public Discounts()
        {
            this.Rel_Discounts_Sizes = new HashSet<Rel_Discounts_Sizes>();
        }
    
        public System.Guid DiscountID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> fk_UserID { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Rel_Discounts_Sizes> Rel_Discounts_Sizes { get; set; }
    }
}
