//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_ProductExcells
    {
        public System.Guid id { get; set; }
        public string excelFilename { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string SubmitIP { get; set; }
        public Nullable<System.Guid> fk_UserIDSubmited { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string ErrorMsg { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
