//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public System.Guid OrderDetailID { get; set; }
        public Nullable<System.Guid> fk_OrderID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.Guid> fk_ProductColorSizeID { get; set; }
    
        public virtual ProductColorSizes ProductColorSizes { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
