//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLogs
    {
        public System.Guid PaymentLogID { get; set; }
        public Nullable<System.Guid> fk_OrderID { get; set; }
        public string RefID { get; set; }
        public Nullable<long> SaleReferenceId { get; set; }
        public Nullable<int> ResCode_Request { get; set; }
        public Nullable<int> ResCode_Payment { get; set; }
        public Nullable<int> ResCode_Verify { get; set; }
        public Nullable<int> ResCode_Settle { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentIP { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
