//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentUniqeCodes
    {
        public int PayementUniqeCodeID { get; set; }
        public System.Guid fk_OrderID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
