//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductColors = new HashSet<ProductColors>();
        }
    
        public System.Guid ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string EN_ProductTitle { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.Guid> fk_ProductGroupID { get; set; }
        public Nullable<int> DesignNo { get; set; }
        public Nullable<int> Frame { get; set; }
        public string Collection { get; set; }
        public string PileType { get; set; }
        public string Reeds { get; set; }
        public string Shots { get; set; }
        public string Points { get; set; }
        public string Knots { get; set; }
        public string EN_Collection { get; set; }
        public string EN_PileType { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsEspecial { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> IsMostSell { get; set; }
        public string Rus_ProductTitle { get; set; }
        public string China_ProductTitle { get; set; }
        public string Rus_Collection { get; set; }
        public string China_Collection { get; set; }
        public string Rus_PileType { get; set; }
        public string China_PileType { get; set; }
        public string ThumbImage1 { get; set; }
        public string ThumbImage2 { get; set; }
        public Nullable<int> ProductUniqeCode { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ProDesc { get; set; }
        public Nullable<bool> IsAlienCulture { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ProductColors> ProductColors { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
