//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductColorSizes
    {
        public ProductColorSizes()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public System.Guid ProductColorSizeID { get; set; }
        public System.Guid fk_ProductColorID { get; set; }
        public int fk_SizeID { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ProductColors ProductColors { get; set; }
        public virtual SIzes SIzes { get; set; }
    }
}
