//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIzes
    {
        public SIzes()
        {
            this.ProductColorSizes = new HashSet<ProductColorSizes>();
            this.Rel_Discounts_Sizes = new HashSet<Rel_Discounts_Sizes>();
        }
    
        public int SizeID { get; set; }
        public string SizeTitle { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<ProductColorSizes> ProductColorSizes { get; set; }
        public virtual ICollection<Rel_Discounts_Sizes> Rel_Discounts_Sizes { get; set; }
    }
}
