//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketResponse
    {
        public System.Guid TicketResponseID { get; set; }
        public Nullable<System.Guid> fk_TicketID { get; set; }
        public string ResponseText { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<System.Guid> fk_UserID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
