//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashadCarpet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitCounter
    {
        public int VisitID { get; set; }
        public string ClientIP { get; set; }
        public string OS { get; set; }
        public string Browser { get; set; }
        public string RefrallPage { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> TotalVisit { get; set; }
        public Nullable<int> VisitCount { get; set; }
    }
}
