//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به سبد خرید.
        /// </summary>
        internal static string AddToBasket {
            get {
                return ResourceManager.GetString("AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به پنل مدیریت.
        /// </summary>
        internal static string Adminlogin {
            get {
                return ResourceManager.GetString("Adminlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ ها.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ های موجود.
        /// </summary>
        internal static string AvailableColors {
            get {
                return ResourceManager.GetString("AvailableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز های موجود.
        /// </summary>
        internal static string AvailableSize {
            get {
                return ResourceManager.GetString("AvailableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب وبلاگ.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بلاگ.
        /// </summary>
        internal static string BlogGroup {
            get {
                return ResourceManager.GetString("BlogGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گواهینامه های استاندارد.
        /// </summary>
        internal static string CertificationStandard {
            get {
                return ResourceManager.GetString("CertificationStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام کلیک.
        /// </summary>
        internal static string ClickForRegister {
            get {
                return ResourceManager.GetString("ClickForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانواده.
        /// </summary>
        internal static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر رنگ.
        /// </summary>
        internal static string Colorfilter {
            get {
                return ResourceManager.GetString("Colorfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم تماس با ما.
        /// </summary>
        internal static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        internal static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه.
        /// </summary>
        internal static string Continuation {
            get {
                return ResourceManager.GetString("Continuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشگاه مشتریان.
        /// </summary>
        internal static string CustomerClub {
            get {
                return ResourceManager.GetString("CustomerClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات مشتریان.
        /// </summary>
        internal static string CustomerServicesTitle {
            get {
                return ResourceManager.GetString("CustomerServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی.
        /// </summary>
        internal static string Dearuser {
            get {
                return ResourceManager.GetString("Dearuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نقشه.
        /// </summary>
        internal static string DesignNo {
            get {
                return ResourceManager.GetString("DesignNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنید.
        /// </summary>
        internal static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید شما خالی است.
        /// </summary>
        internal static string EmptyBasket {
            get {
                return ResourceManager.GetString("EmptyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر را وارد نمایید.
        /// </summary>
        internal static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را صحیح وارد نمایید.
        /// </summary>
        internal static string EnterCorrectEmail {
            get {
                return ResourceManager.GetString("EnterCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را وارد نمایید.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی را وارد نمایید.
        /// </summary>
        internal static string EnterFamily {
            get {
                return ResourceManager.GetString("EnterFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام را وارد نمایید.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن را وارد نمایید.
        /// </summary>
        internal static string EnterText {
            get {
                return ResourceManager.GetString("EnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن تیکت را وارد نمایید.
        /// </summary>
        internal static string EnterTicketText {
            get {
                return ResourceManager.GetString("EnterTicketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور خود را وارد نمایید..
        /// </summary>
        internal static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود فاکتور.
        /// </summary>
        internal static string FactorDownload {
            get {
                return ResourceManager.GetString("FactorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهایی شدن فاکتور.
        /// </summary>
        internal static string Factorfinal {
            get {
                return ResourceManager.GetString("Factorfinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارخانه فرش مشهد.
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور شما نهایی شده است..
        /// </summary>
        internal static string FinalizedFactor {
            get {
                return ResourceManager.GetString("FinalizedFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور خود را فراموش کرده اید؟.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینجا.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه است..
        /// </summary>
        internal static string IncorrectUsernameOrPass {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل معتبر نمی باشد.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست فاکتورها.
        /// </summary>
        internal static string InvoicesList {
            get {
                return ResourceManager.GetString("InvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده؟.
        /// </summary>
        internal static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارس.
        /// </summary>
        internal static string labeltext {
            get {
                return ResourceManager.GetString("labeltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدیدترین اخبار.
        /// </summary>
        internal static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک های مفید.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت دسترسی به این بخش، باید وارد سایت شوید..
        /// </summary>
        internal static string LoginForAccess {
            get {
                return ResourceManager.GetString("LoginForAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سایت.
        /// </summary>
        internal static string LoginToSite {
            get {
                return ResourceManager.GetString("LoginToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/Logo2.png.
        /// </summary>
        internal static string logoimg {
            get {
                return ResourceManager.GetString("logoimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع فرش ماشینی.
        /// </summary>
        internal static string machinecarpetmodel {
            get {
                return ResourceManager.GetString("machinecarpetmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه ها.
        /// </summary>
        internal static string Markets {
            get {
                return ResourceManager.GetString("Markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرش مشهد.
        /// </summary>
        internal static string MashadCarpet {
            get {
                return ResourceManager.GetString("MashadCarpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرش مشهد، فرش برتر.
        /// </summary>
        internal static string MashadCarpetDevice {
            get {
                return ResourceManager.GetString("MashadCarpetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر مرکزی فرش مشهد.
        /// </summary>
        internal static string Mashhadcarpetheadquarters {
            get {
                return ResourceManager.GetString("Mashhadcarpetheadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارخانجات گروه صنعتی مشهد.
        /// </summary>
        internal static string MashhadIndustrialGroupFactories {
            get {
                return ResourceManager.GetString("MashhadIndustrialGroupFactories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب من.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید فرش ماشینی.
        /// </summary>
        internal static string NewestProductTitle {
            get {
                return ResourceManager.GetString("NewestProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار و تازه ها.
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولی جهت نمایش موجود نمی باشد.
        /// </summary>
        internal static string NotAvailableProduct {
            get {
                return ResourceManager.GetString("NotAvailableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت آنلاین.
        /// </summary>
        internal static string OnlibePayment {
            get {
                return ResourceManager.GetString("OnlibePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده محصولات.
        /// </summary>
        internal static string onlineshopping {
            get {
                return ResourceManager.GetString("onlineshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه اینترنتی.
        /// </summary>
        internal static string OnlineStore {
            get {
                return ResourceManager.GetString("OnlineStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سفارش.
        /// </summary>
        internal static string orderdate {
            get {
                return ResourceManager.GetString("orderdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه سفارشات.
        /// </summary>
        internal static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتخارات ما.
        /// </summary>
        internal static string OurAwards {
            get {
                return ResourceManager.GetString("OurAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        internal static string PayMent {
            get {
                return ResourceManager.GetString("PayMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش پرداخت ها.
        /// </summary>
        internal static string Paymentsreport {
            get {
                return ResourceManager.GetString("Paymentsreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخصی.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نقشه.
        /// </summary>
        internal static string plannumber {
            get {
                return ResourceManager.GetString("plannumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پربازدیدترین اخبار.
        /// </summary>
        internal static string PopularNews {
            get {
                return ResourceManager.GetString("PopularNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        internal static string Postalcode {
            get {
                return ResourceManager.GetString("Postalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت (با تخفیف).
        /// </summary>
        internal static string PriceAfterDiscount {
            get {
                return ResourceManager.GetString("PriceAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فی.
        /// </summary>
        internal static string Priceper {
            get {
                return ResourceManager.GetString("Priceper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی محصولات.
        /// </summary>
        internal static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محصول.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه محصولات.
        /// </summary>
        internal static string ProductsGroup {
            get {
                return ResourceManager.GetString("ProductsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات محصول.
        /// </summary>
        internal static string ProductSpecifications {
            get {
                return ResourceManager.GetString("ProductSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        internal static string ProductsTitle {
            get {
                return ResourceManager.GetString("ProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنمای خرید.
        /// </summary>
        internal static string Purchaseguide {
            get {
                return ResourceManager.GetString("Purchaseguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکم.
        /// </summary>
        internal static string Reeds {
            get {
                return ResourceManager.GetString("Reeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلاگ های مشابه.
        /// </summary>
        internal static string RelatedBlogs {
            get {
                return ResourceManager.GetString("RelatedBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات مشابه.
        /// </summary>
        internal static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه مورد نظر را وارد نمایید..
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید.
        /// </summary>
        internal static string shoppingbag {
            get {
                return ResourceManager.GetString("shoppingbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شانه.
        /// </summary>
        internal static string shots {
            get {
                return ResourceManager.GetString("shots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده جزئیات .
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده لیست سفارشات.
        /// </summary>
        internal static string ShowOrderList {
            get {
                return ResourceManager.GetString("ShowOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده جزئیات محصول.
        /// </summary>
        internal static string ShowProductDetail {
            get {
                return ResourceManager.GetString("ShowProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده محصولات.
        /// </summary>
        internal static string ShowProducts {
            get {
                return ResourceManager.GetString("ShowProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر سایز.
        /// </summary>
        internal static string SizeFilter {
            get {
                return ResourceManager.GetString("SizeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئولیت اجتماعی.
        /// </summary>
        internal static string SocialResponsibility {
            get {
                return ResourceManager.GetString("SocialResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        internal static string StoreAddress {
            get {
                return ResourceManager.GetString("StoreAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        internal static string StoreCity {
            get {
                return ResourceManager.GetString("StoreCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فروشگاه.
        /// </summary>
        internal static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        internal static string StorePhone {
            get {
                return ResourceManager.GetString("StorePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال تیکت.
        /// </summary>
        internal static string SubmitTicket {
            get {
                return ResourceManager.GetString("SubmitTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت ارسال شد..
        /// </summary>
        internal static string SuccessfulMessage {
            get {
                return ResourceManager.GetString("SuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام شما با موفقیت صورت پذیرفت.
        /// </summary>
        internal static string SuccessfulRegister {
            get {
                return ResourceManager.GetString("SuccessfulRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال تیکت پشتیبانی.
        /// </summary>
        internal static string SupportKnowledgebase {
            get {
                return ResourceManager.GetString("SupportKnowledgebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالیات.
        /// </summary>
        internal static string TaxTitle {
            get {
                return ResourceManager.GetString("TaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط و قوانین.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با تشکر.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تیکت.
        /// </summary>
        internal static string TicketDate {
            get {
                return ResourceManager.GetString("TicketDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست تیکت ها.
        /// </summary>
        internal static string TicketsList {
            get {
                return ResourceManager.GetString("TicketsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع تیکت.
        /// </summary>
        internal static string TicketSubject {
            get {
                return ResourceManager.GetString("TicketSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن تیکت.
        /// </summary>
        internal static string TicketText {
            get {
                return ResourceManager.GetString("TicketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع فاکتور.
        /// </summary>
        internal static string Totalfactor {
            get {
                return ResourceManager.GetString("Totalfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیگیری.
        /// </summary>
        internal static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیگیری خرید.
        /// </summary>
        internal static string TrackOrder {
            get {
                return ResourceManager.GetString("TrackOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز رسانی سبد خرید.
        /// </summary>
        internal static string UpdateBasket {
            get {
                return ResourceManager.GetString("UpdateBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده سبد خرید.
        /// </summary>
        internal static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        internal static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        internal static string VisitTitle {
            get {
                return ResourceManager.GetString("VisitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به وب سایت فرش مشهد خوش آمدید.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته شده توسط.
        /// </summary>
        internal static string WrittenBy {
            get {
                return ResourceManager.GetString("WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش برای شما ثبت شده است.
        /// </summary>
        internal static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید شما.
        /// </summary>
        internal static string YourShoppingCart {
            get {
                return ResourceManager.GetString("YourShoppingCart", resourceCulture);
            }
        }
    }
}
